version: '3'

networks:
  locust:
    driver: bridge

services:
  master:
    image: metafox-locust
    restart: always
    build: .
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    networks:
      - locust

    command: -f /mnt/locust/locustfile/home.py --master --host 'https://production.metafox.app'

  worker:
    image: foxstystem/locust
    build: .
    depends_on:
      - master
    networks:
      - locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/pages/home.py --worker --master-host master

